### ISSUE TITLE
Background not working

### ISSUE THREAD

**Issue by tomjmul** [basnijholt/lovelace-ios-themes#20]
I'm new to all of this, so fogive me if I'm doing something wrong here - the variable background-image doesn't seem to be working for me. I installed the theme through HACS, and everything in the view does seem to be themed correctly except there is a white background.

I added `background: var(--background-image)` to the top in Raw Configuration Editor.

If I substitute the variable value itself, e.g: `background: "center / cover no-repeat fixed url('/hacsfiles/themes/ios-themes/homekit-bg-dark-green.jpg')"`, then that works and everything looks great.

**Comment by smithjames0** [comment]
I also have the same issue, I installed this today and I cannot get the background to work.

**Comment by jemberton** [comment]
I had the same issue initially. I was setting the theme for the card/page, not the profile. See [this post](https://github.com/basnijholt/lovelace-ios-themes/issues/18#issuecomment-718546852)

**Comment by tomjmul** [comment]
Thanks a lot for the pointer @jemberton  

Closing this as duplicate of #18

**Comment by asemev** [comment]
hi guys, my background image used to work but since some while its not showing anymore. I'm setting the theme from the profile page (not panel). thats how it has always been. didnt change anything. the theme files are all in the same folder as before. i removed and re-installed and still the background image is not showing. any clues?
